### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mcmillanator** [mcmillanator/4.3-rails-model#1]
### Deliverables
* [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `4.3 - Rails-Model -- YOUR NAME` with checkboxes as below under _Requirements_.
* A repository named `4.3-Rails-Model` containing at least a `README.md` file
* A Pull Request (PR) in your `4.3-Rails-Model` repo:
  * _from_ branch `dev`
  * _into_ branch master
* A comment on your original Issue with a link to your PR

### Requirements
* Create new `postgresql` Rails project
* Generate an `Album` model
  * `title`, `artist`, `genre`, `length`
* Add validations to ensure no fields are blank
* Add validation to ensure length > 0
* Add validation for `title` & `artist` to not have duplicates
* Ensure calling `album.save` actually saves to the database
* Write tests for these validations

### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Rails-Model-4.3` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create data model/specs
  - [x] Checkpoint: Created new `postgresql` Rails project
  - [x] Checkpoint: Generated an `Album` model with `title:string`, `artist:string`, `genre:string`, `length:integer`
  - [x] Checkpoint: Added validations to ensure no fields are blank
  - [x] Checkpoint: Added validation to ensure length > 0
  - [x] Checkpoint: Added validation for `title` & `artist` to not have duplicates
  - [x] Checkpoint: Ensured calling `album.save` actually saves to the database
  - [x] Checkpoint: Wrote tests for these validations
  - [x] Complete: pushed all relevant code
